
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Lightbulb, Recycle, Zap, Droplets, Globe } from "lucide-react";

const educationalTopics = [
  {
    icon: <Globe className="h-6 w-6 text-primary" />,
    title: "Understanding Carbon Footprint",
    description: "Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by your actions. For products, this includes emissions from raw material extraction, manufacturing, transportation, use, and disposal.",
    tips: [
      "Choose products made with renewable energy.",
      "Opt for locally sourced items to reduce transportation emissions.",
      "Consider the energy efficiency of appliances during their use phase.",
    ],
  },
  {
    icon: <Droplets className="h-6 w-6 text-primary" />,
    title: "Water Usage & Conservation",
    description: "Water usage, or water footprint, refers to the amount of fresh water utilized in the production or supply of goods and services. This includes direct water use (e.g., in manufacturing) and indirect water use (e.g., for growing raw materials like cotton).",
    tips: [
      "Support products made from less water-intensive materials (e.g., linen over conventional cotton).",
      "Be mindful of products from water-scarce regions.",
      "Repair leaks at home to conserve water directly.",
    ],
  },
  {
    icon: <Recycle className="h-6 w-6 text-primary" />,
    title: "Sustainable Materials & Recyclability",
    description: "Sustainable materials are sourced or produced in a way that minimizes environmental harm. This includes recycled content, renewable resources (like bamboo or cork), and materials that are biodegradable or easily recyclable at the end of their life.",
    tips: [
      "Look for products made from recycled materials (e.g., rPET, recycled metal).",
      "Choose items designed for durability and repairability.",
      "Check local recycling guidelines to ensure proper disposal.",
    ],
  },
  {
    icon: <Zap className="h-6 w-6 text-primary" />,
    title: "Energy Efficiency",
    description: "Energy efficiency means using less energy to perform the same task. For products, this can relate to the energy used during manufacturing or the energy consumed during the product's lifespan (e.g., appliances, electronics).",
    tips: [
      "Look for energy rating labels like Energy Star.",
      "Unplug electronics when not in use to avoid 'phantom load'.",
      "Choose LED lighting over incandescent bulbs.",
    ],
  },
];

export default function EducationalContent() {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold font-headline text-primary mb-2">Learn About Sustainability</h1>
        <p className="text-lg text-muted-foreground">
          Empower yourself with knowledge to make more eco-conscious decisions.
        </p>
      </div>

      {educationalTopics.map((topic, index) => (
        <Card key={index} className="shadow-lg">
          <CardHeader>
            <div className="flex items-center gap-3">
              {topic.icon}
              <CardTitle className="font-headline text-2xl">{topic.title}</CardTitle>
            </div>
            <CardDescription className="pt-2 text-base">{topic.description}</CardDescription>
          </CardHeader>
          <CardContent>
            <h4 className="font-semibold text-lg mb-2 flex items-center gap-2">
              <Lightbulb className="h-5 w-5 text-accent" />
              Quick Tips:
            </h4>
            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
              {topic.tips.map((tip, tipIndex) => (
                <li key={tipIndex}>{tip}</li>
              ))}
            </ul>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
